services:
  angular-app:
    build: .
    ports:
      - "4200:80"
    container_name: angular-app-container
    volumes:
      - ./public/assets/config.json:/usr/share/nginx/html/browser/assets/config.json
